SET statement_timeout=0;
\copy gps.ee_species_limited (abbr , english_name , latin_name , species_id) FROM 'ee_species_limited.csv'
\copy gps.ee_individual_limited (ring_number , species_latin_name , colour_ring , mass , remarks , sex , start_date , end_date , individual_id) FROM 'ee_individual_limited.csv'
\copy gps.ee_project_limited (key_name , station_name , start_date , end_date , description , project_id , parent_id) FROM 'ee_project_limited.csv'
\copy gps.ee_tracker_limited (device_info_serial , firmware_version , mass , start_date , end_date , x_o , x_s , y_o , y_s , z_o , z_s , tracker_id) FROM 'ee_tracker_limited.csv'
\copy gps.ee_track_session_limited (key_name , device_info_serial , ring_number , start_date , end_date , start_latitude , start_longitude , remarks , track_session_id , project_id , tracker_id , individual_id) FROM 'ee_track_session_limited.csv'
\copy gps.ee_tracking_speed_limited (the_geom, the_geom_webmercator , device_info_serial , date_time , latitude , longitude , altitude , pressure , temperature , satellites_used , gps_fixtime , positiondop , h_accuracy , v_accuracy , x_speed , y_speed , z_speed , speed_accuracy , speed_3d , speed_2d , direction , altitude_agl) FROM program 'gunzip -c ee_tracking_speed_limited.csv'
